version: '3'

services:
  file-service:
    build: .
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      - STORAGE_TYPE=s3
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - S3_ENDPOINT=s3:9000  # Изменено с http://s3:9000
    depends_on:
      - s3

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - s3-data:/data

volumes:
  s3-data: